### ISSUE TITLE
Suggestion to Hosting Civbuilder

### ISSUE THREAD

**Issue by YK-TIGER** [joyhyunki/civbuilder#1]
You can host the website using Github. Go to the settings of this repository, and find 'Github Pages'. then you can host the website using Github.

**Comment by joyhyunki** [comment]
https://joyhyunki.github.io/civbuilder/
Come visit my site, comrade.

**Comment by joyhyunki** [comment]
Wanna work with me? Should I give you access to editing this project? Consider it 👍
